### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by doublee313** [Lacyway/V-Rising-Server-Manager#11]
Can you please add discord support for:

Auto-Updates
Auto-Restarts
Server Start
Server Stop

I'm using a Discord bot off Nexus for the other (cross-chat) so if you had the basics above, that would cater to your managers activity :)

Thanks and it's running great!

**Comment by doublee313** [comment]
It would be nice if we could edit the messages as well to add emojis, etc

🟢 Server is starting
🛑 Server as stopped

etc :)

**Comment by Lacyway** [comment]
This might not be easy to implement, but I will have a look.

**Comment by doublee313** [comment]
Thanks. A webhook would be sufficient to post the Discord alerts. I'm no coder, so good luck :)

**Comment by Lacyway** [comment]
Figured out a way to do it, adding it tomorrow. Thanks for the suggestion.

**Comment by Lacyway** [comment]
Added in 1.3

**Comment by doublee313** [comment]
Testing now. Thank you! Start..Stop works.....You are awesome for taking suggestions and making them happen.

If you can add a "TEST" button in the Discord part, it might help some test to make sure the hook works, etc.

**Comment by Lacyway** [comment]
Thank you.
I've added a test button for the next release.
