### ISSUE TITLE
Server Settings Editor are not saving some specific configurations.

### ISSUE THREAD

**Issue by DaavyC** [Lacyway/V-Rising-Server-Manager#19]
I am setting up one dedicated server using this manager _(who I found so useful and practical)_ and settings like Description, RCON Password and Password himself _(Server password)_ just don't save using the editor.

I'm not started changing Game Settings with the manager editor yet, if I found the same problems I will inform.

**Comment by Lacyway** [comment]
I think I've been able to reproduce this. Make sure that before you save, click another field or a few of them so that it properly saves the value of the current field. Might find a fix for this in the future.

**Comment by Lacyway** [comment]
Should be fixed with semi-MVVM implementation.
