### ISSUE TITLE
Server restart warning not firing 

### ISSUE THREAD

**Issue by srtzero** [Lacyway/V-Rising-Server-Manager#20]
The 5 minute warning to players that the server will restart is not firing off in RCON. Even after saving RCON settings. Server just restarts without any warnings.

**Comment by Lacyway** [comment]
Sorry about the late reply. For some reason I did not receive any notifications.
Are you still having this issue?

**Comment by srtzero** [comment]
Yes. Still having issue

**Comment by Lacyway** [comment]
Would you be able to test any RCON commands with the RCON console to see if they go through?
I won't be able to test it locally for a bit. If you could test that for me that'd be a big help.

**Comment by srtzero** [comment]
I can send messages with rcon no problem. Its just the auto warning doesnt fire for the auto restart server option. But I can test commands if you need me too. Just let me know which ones.

**Comment by Lacyway** [comment]
I'll try my best to test what could be wrong soon. Been busy with real life and kind of lost interest in V Rising, but if I have some spare time I'll investigate.

Sorry about that.

**Comment by srtzero** [comment]
No worries. Most of my players know now when it will restart, so kind of used to it. But it would be nice if and when you have the time. Thanks.

**Comment by Lacyway** [comment]
Should be fixed post 3.0 release
