### ISSUE TITLE
Several servers in same .exe

### ISSUE THREAD

**Issue by MickyOver** [Lacyway/V-Rising-Server-Manager#22]
First of all, thanks for your work. I gues that GUI is super usefull, I like it.
I my case, I provide to the gaming community free of charge and selflessly several servers, so could be so useful to have in the same .exe several tabs (each one for each server).

Thanks in advance.

**Comment by Lacyway** [comment]
Sounds like a good idea, I will see if I can make this but might be quite a project so unsure how long it would take.

**Comment by MickyOver** [comment]
Yep, I know a little bit about coding and know too that if something sounds like "copy-paste"... usually it is not xD
But, yeah, if you can implement the idea cool :)

**Comment by Lacyway** [comment]
I've spent this week rewriting most of it and I'd say I'm 80% done. Hopefully I can push a new release this weekend. The multiple servers in tabs work already and it's way more responsive than before 👍

**Comment by Lacyway** [comment]
I've released a new version adding this.
See [v3.0-beta](https://github.com/Lacyway/V-Rising-Server-Manager/releases/tag/v3.0-beta).
