### ISSUE TITLE
Self-Updater Target URL 404 for Latest Release

### ISSUE THREAD

**Issue by komori** [Lacyway/V-Rising-Server-Manager#24]
It seems like the latest releases' built package didn't make it on the latest release (v3.3.2b) post.

On startup, my v3.2.1b release notified me of the new version (v3.3.2b) and offered update as usual, but immediately after the download confirmation prompt it fails, prints some errors, and promptly closes the program.

Taking a closer look it the update download URL, [https://github.com/Lacyway/V-Rising-Server-Manager/releases/latest/download/VSM.zip](https://github.com/Lacyway/V-Rising-Server-Manager/releases/latest/download/VSM.zip), redirects and resolves to [https://github.com/Lacyway/V-Rising-Server-Manager/releases/download/v3.3.2-beta/VSM.zip](https://github.com/Lacyway/V-Rising-Server-Manager/releases/download/v3.3.2-beta/VSM.zip), which returns a 404 from Github causing the abrupt program exit.

I'm not waiting on any fix or changes--the current feature set is much more than I could've hoped for when I stumbled across VSM last weekend--3.2.1b has smooth sailing for me. I mostly wanted to give a quick heads-up if v3.3.2b was released in rushed circumstances for whatever reason and the missing package zip was just overlooked.

That, and I definitely wanted to say "thank you!" and voice my appreciation for sharing your project here. I work in IT, on the net-eng portion of the field, so I was getting _very_ exasperated with the current state of deprecated and incomplete official documentation. Mostly due to my inability to get a darned simple gameserver up, running & listed from a win VM running on a Proxmox host at home. Granted, I was trying to hustle through it, but using a disjointed array of various forum posts, gaming blogs, document fragments on github, etc was an easy target for the lack of prompt success.

Anyhoow, I've since sorted out which options were deprecated and causing my problems, but VSM and your, albeit brief, setup wiki got me up and running on the first pass. It was so painless and easy that I was skeptical the server was functional when I first saw the listing appear in-game. It's been great for me since. The only snag I've found is the automatic gameserver update process appeared to leave a process running that held onto udp/9876-9877 causing conflict when it tries to launch the updated server. I'm not even certain root cause was VSM, so I'll turn auto-updates back on in the near future or pull an older version via steamcmd and let VSM update it while logging all the things and let you know what role VSM plays--if any--in the failure to re-launch. I've rambled enough, so one last hurrah for this little beacon of light in a sea of partially deprecated and incomplete documentation. I've got two worlds humming along nice stable, oh, and the tooltips for each game setting are such an stellar time-saver and amazing QoL feature as someone new to the game, thanks again!

**Comment by Lacyway** [comment]
At a closer look it should only be using port 80 and 443, but if it happens again let me know and I'll set a timeout to ~2 minutes according to [the documentation](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#dns-behavior) and see if that helps.

**Comment by komori** [comment]
> I'll have a look at the Wiki soon, I kind of updated it very sloppy after >3.0 because there were so many changes and time is a luxury these days.
Ah, I was ranting about Stunlock's documentation, or lack thereof. I know they're considered an "indie" studio, but I'd think ensuring a smooth process for their customers who are trying to use their own resources running game servers would be a fairly significant priority. Your documentation, on the other hand, has been on-point and plenty thorough--I followed the steps and it produced [two] stable servers that have ran great since the first time they were fired up through VSM.

The self-update worked great, running v3.3.2b now. I haven't spent the time to create a new out-of-date server to test the update process to investigate the port conflict yet. But I do have whatever debug & logging options I could find turned up so I should get something when Stunlock pushes the next patch. Thanks again!

**Comment by aishuocuohuadedashu** [comment]
> 谢谢你的溢美之词！
> 
> 我好像错过上传了，谢谢告知。我已经上传了。
> 
> 我很快会看一下维基，我在3.0之后更新得很草率，因为有太多的变化，这些天时间是一种奢侈。
> 
> 那些端口上的进程必须是**HttpClient**向steamcmd.net发送GET请求以获取最新的更新时间，根据文档，它们不应该被处理掉，但是我担心类似这样的事情最终会发生。在我使用SteamCMD并读取所有输出之前，我注意到它是如此的不一致和缓慢，所以我最近求助于这个解决方案。如果它再次发生，请让我知道，我将不得不寻找一个替代的解决方案**HttpClient**。👍

**Comment by aishuocuohuadedashu** [comment]
I would like to ask you, my own server can not be displayed in the public list, the steam game list can be seen." ListOnSteam": true, "ListOnEOS": true, these two files are set and are not displayed

**Comment by Lacyway** [comment]
> I would like to ask you, my own server can not be displayed in the public list, the steam game list can be seen." ListOnSteam": true, "ListOnEOS": true, these two files are set and are not displayed

This is an issue with the game that has been a problem since release for me too. Sometimes it works, sometimes it doesn't. Make sure ports are open and sometimes it takes ~5 minutes until it appears. Otherwise I'd advise you to check if someone can help you on the Official VRising Discord, I see people posting this problem every now and then and maybe they've found a solution.

**Comment by aishuocuohuadedashu** [comment]
> > I would like to ask you, my own server can not be displayed in the public list, the steam game list can be seen." ListOnSteam": true, "ListOnEOS": true, these two files are set and are not displayed
> 
> This is an issue with the game that has been a problem since release for me too. Sometimes it works, sometimes it doesn't. Make sure ports are open and sometimes it takes ~5 minutes until it appears. Otherwise I'd advise you to check if someone can help you on the Official VRising Discord, I see people posting this problem every now and then and maybe they've found a solution.

I have not found an effective way, the server has not appeared in the public list, I came here for help! I am a Chinese gamer, because some networks are not accessible, so I come here for help

**Comment by Lacyway** [comment]
> > > I would like to ask you, my own server can not be displayed in the public list, the steam game list can be seen." ListOnSteam": true, "ListOnEOS": true, these two files are set and are not displayed
> > 
> > 
> > This is an issue with the game that has been a problem since release for me too. Sometimes it works, sometimes it doesn't. Make sure ports are open and sometimes it takes ~5 minutes until it appears. Otherwise I'd advise you to check if someone can help you on the Official VRising Discord, I see people posting this problem every now and then and maybe they've found a solution.
> 
> I have not found an effective way, the server has not appeared in the public list, I came here for help! I am a Chinese gamer, because some networks are not accessible, so I come here for help

You could try changing the game and query port to something else, like 27015 and 27016. That seems to have worked for some people. 

There is not much else I can do to assist, sorry. It's an issue with the game.
