### ISSUE TITLE
Name server issue

### ISSUE THREAD

**Issue by richexpert** [Lacyway/V-Rising-Server-Manager#25]
first off thank you very much for the awesome manager, we're going to have the best tool ever running 100% 

issue: when i set name for +add server this name appears at game list as name server not the name server configured/set inside manager. I dunno if its a real issue or maybe its with me only.

Anyways thanks for the awesome tool!

**Comment by Lacyway** [comment]
Thank you for the kind words. :)

Can you send a screenshot of the manager when you have that server selected and then a screenshot of the server name in-game? Thanks!

**Comment by richexpert** [comment]
Sure !

![image](https://github.com/Lacyway/V-Rising-Server-Manager/assets/30881817/63c25a01-feb3-4e42-9c58-37673464546e)
![image](https://github.com/Lacyway/V-Rising-Server-Manager/assets/30881817/37ce575c-f0ca-456d-becf-758d69230ac4)
![image](https://github.com/Lacyway/V-Rising-Server-Manager/assets/30881817/bf5c3f67-bbb3-49da-af9e-95829546c701)
![image](https://github.com/Lacyway/V-Rising-Server-Manager/assets/30881817/acbd2e98-7cd9-4aef-9311-0c5ad709ae16)

**Comment by Lacyway** [comment]
You're right, it's using the "Name" and not "DisplayName". Can't believe I missed that.
I've uploaded a new version, can you try it and see if it resolves it?

Thanks!

**Comment by richexpert** [comment]
Sure, with pleasure !
tested and its working thanks ^^

may i suggest a function? but i dunno if its possible to implement or if its necessary.

- its possible to make manage admin button to bring a screen where you see all players logged in so we can manage those players directly in this screen too? (click on them mute/kick/ban/perm ban/etc) i dunno if its necessary, just an idea
- also with the same function make player name become red in this panel when a player spawn an item or send commands like admin, kinda manually "anti-cheater detect" helper. So if a player isnt an admin and they name became red we know this person is cheating.

thanks again for your awesome work!

**Comment by Lacyway** [comment]
I don't think it's very possible yet due to how little RCON commands there are, so unfortunately not at the moment.
If they ever add more RCON commands I will definitely have a look at it.

Thanks again for the bug report, please let me know if you notice anything else. :)
