### ISSUE TITLE
Auto start server option

### ISSUE THREAD

**Issue by pickledrange** [Lacyway/V-Rising-Server-Manager#27]
Would it be possible to add an option to auto start the server when the app is launched?
I run my server from a local PC and id like the server to start when i turn on the machine without having to remote in an press start :)

**Comment by Lacyway** [comment]
I've added it to the latest release, please try it and let me know if there are any problems. From my testing it worked as intended, but I might've missed something.

Thanks :)

**Comment by pickledrange** [comment]
Working perfectly this end, love it thanks :)
