### ISSUE TITLE
VSM closes

### ISSUE THREAD

**Issue by raedan01** [Lacyway/V-Rising-Server-Manager#28]
First of all I love this utility, thank you very much for making it.

When I click "Install BepInEx" I get an hourglass for a few seconds then VSM closes. BepInEx does not get installed.

Also Host settings missing "ListOnMasterServer"?

**Comment by Lacyway** [comment]
> First of all I love this utility, thank you very much for making it.
> 
> When I click "Install BepInEx" I get an hourglass for a few seconds then VSM closes. BepInEx does not get installed.
> 
> Also Host settings missing "ListOnMasterServer"?

Thank you!

Iirc `ListOnMasterServer `is deprecated and it's `ListOnSteam` and `ListOnEOS `now.

Regarding the crash, it seems like they changed the name of the mod and the way the launcher detects it requires it to use the old name. I'll look into fixing it when I can, but for now you can download the mod manually and then click "Install BepinEx".

It's the one in the picture below, just click download on it and then click the install button at the top right, not in the mod view.
![image](https://github.com/Lacyway/V-Rising-Server-Manager/assets/20912169/4d16230b-f50a-426f-95ad-6536f6110b2b)

**Comment by raedan01** [comment]
Thank you I wasn't expecting such a quick reply. 
Unfortunately it doesn't like that. I get "Install - Error" "BepInEx-BepInExPack_V_Rising is not supported".
No worries, thank you, Have a good day.

**Comment by Lacyway** [comment]
> Thank you I wasn't expecting such a quick reply. 
> Unfortunately it doesn't like that. I get "Install - Error" "BepInEx-BepInExPack_V_Rising is not supported".
> No worries, thank you, Have a good day.

Just click "Download" and it should work. After it is downloaded click "Install BepInEx" at the top right, not next to the download button. 😊

I've fixed it for the next release.

**Comment by raedan01** [comment]
The download does work for sure. I tried both install buttons. The error previously was indeed with the install button next to the download button.

I also tried the top install button after downloading and it just closes after a couple seconds after the initial yes/no dialog.

No big deal seriously, I appreciate it, I'll wait until your next release. I hope you have a good weekend though.  =)

Again awesome server utility, There are not many out there. A couple others I have used are Conan Exiles Dedicated Server Launcher and ValheimServerGUI. Yours is the first one I've seen of this type with config editors and mod installer.

**Comment by Lacyway** [comment]
Could you see if the latest release [v3.3.5-beta](https://github.com/Lacyway/V-Rising-Server-Manager/releases/tag/v3.3.5-beta) fixes this? I've been able to reproduce it several times and each time it has worked with the new release.

If not, let me know. There is a short workaround to fix it in the `VSMSettings.json` file. Look for a `DownloadedMods` entry with `Uuid4` **b86fcaaf-297a-45c8-82a0-fcbd7806fdc4** that has no `ArchiveName` and remove it. In my case it is what I marked below:

![image](https://github.com/Lacyway/V-Rising-Server-Manager/assets/20912169/04ef6614-7210-4c93-8c23-8d99f6ce9db8)

**Comment by raedan01** [comment]
Ok long story short it works, fantastic.

I did have 1 issue, I have(had) server manager on my D:\ and my server on my F:\
It complained about them not being in the same path and errored out.
I moved Server manager to F:\ and it worked.
So currently Server manager is in F:\VSM and the Server is in F:\VSM.Server.
I installed about half a dozen mods and I was only able to test one easily but it works also.

**Comment by Lacyway** [comment]
> Ok long story short it works, fantastic.
> 
> I did have 1 issue, I have(had) server manager on my D:\ and my server on my F: It complained about them not being in the same path and errored out. I moved Server manager to F:\ and it worked. So currently Server manager is in F:\VSM and the Server is in F:\VSM.Server. I installed about half a dozen mods and I was only able to test one easily but it works also.

Ok, thanks for letting me know.
I'll try testing having the server on another drive a bit myself... Haven't really thought of that.

**Comment by raedan01** [comment]
That's what makes it fun.
