### ISSUE TITLE
Ui on Windows 11 is funky

### ISSUE THREAD

**Issue by LoGicMoTion** [Lacyway/V-Rising-Server-Manager#7]
The Ui for the app is a little weird for me hoping it could be fix: [image here](https://i.imgur.com/9ykcBXa.jpg)

**Comment by Lacyway** [comment]
Are you running a higher DPI than 100%? I don't think the GUI scales well, but I could make it more readable.

**Comment by LoGicMoTion** [comment]
I am its running at 150%
That fix worked thank you but its still a little blurry, but no big deal!
Thank you Lacy and awesome software you made
