### ISSUE TITLE
Add auto-updater

### ISSUE THREAD

**Issue by Lacyway** [Lacyway/V-Rising-Server-Manager#8]

**Comment by doublee313** [comment]
This would be very nice. I will start testing this awesome manager this week! Nice work. 

If you can add this for auto-update:

Check every xx 
Manual check with or without Verify option

Thanks!

**Comment by Lacyway** [comment]
> 

Thank you, I've already implemented it but just need to test it a bit further. Seems like it will be working fine.
I will add a checkmark for "Verify" as well.
